package com.iiyeung.plugin.zentao.extension.zentao.model

import kotlinx.serialization.Serializable

/**
 * @author Yeung
 * @version v1.0
 * @date 2024-01-18 22:25:59
 */
@Serializable()
data class ZentaoBug(
    val id: Int,
    val project: Int,
    val product: Int,
    val injection: Int,
    val identify: Int,
    val branch: Int,
    val module: Int,
    val execution: Int,
    val plan: Int,
    val story: Int,
    val storyVersion: Int,
    val task: Int,
    val toTask: Int,
    val toStory: Int,
    val title: String,
    val keywords: String,
    val severity: Int,
    val pri: Int,
    val type: String,
    val os: String,
    val browser: String,
    val hardware: String,
    val found: String,
    val steps: String,
    val status: String,
    val subStatus: String,
    val color: String,
    val confirmed: Int,
    val activatedCount: Int,
    val activatedDate: String?,
    val feedbackBy: String,
    val notifyEmail: String,
//    val mailto: List<Any>,
    val openedBy: ZentaoUserInfo,
    val openedDate: String,
    val openedBuild: String,
    val assignedTo: ZentaoUserInfo,
    val assignedDate: String,
//    val deadline: String,
    val resolvedBy: ZentaoUserInfo?,
    val resolution: String,
    val resolvedBuild: String,
    val resolvedDate: String?,
    val closedBy: ZentaoUserInfo?,
    val closedDate: String?,
    val duplicateBug: Int,
    val linkBug: String,
    val case: Int,
    val caseVersion: Int,
    val feedback: Int,
    val result: Int,
    val repo: Int,
    val mr: Int,
    val entry: String,
    val lines: String,
    val v1: String,
    val v2: String,
    val repoType: String,
    val issueKey: String,
    val testtask: Int,
//    val lastEditedBy: ZentaoUserInfo,
//    val lastEditedDate: String,
    val deleted: Boolean,
    val priOrder: String,
    val severityOrder: Int,
//    val delay: Int,
    val needconfirm: Boolean,
    val statusName: String,
    val productStatus: String
)